<?php

/**
 * @category  Deloitte
 * @package   Deloitte_DeveloperTest
 * @author    Deloitte Team <info@deloitte.com>
 * @copyright 2020 Deloitte 
 * @link      https://www2.deloitte.com/
 */

/**
 *
 * @var $block Magento\Framework\View\Element\Template
 */
?>
<div id="popup-modal" style="display:none;">
    <h1> Verify your age before adding product in car. </h1>
    <select id="id-cards" name="cards">
        <option value="1">Pan card</option>
        <option value="2">Aadhar card</option>
        <option value="3">Passport number</option>
        <input id="card-field" name="cart-field">
        <button id="verify-btn" >varify</button>
    </select>
</div>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {

            var popup = modal(options, $('#popup-modal'));
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Verify your add before adding product in cart',
                buttons: [{
                    text: $.mage.__('Continue'),
                    class: '',
                    click: function() {
                        this.closeModal();
                    }
                }]
            };

            $('button.action.tocart.primary').click(function(e) {
                showPopup(e);
                console.log('test');
                event.preventDefault();
            });
           
            function showPopup(e) {
                $("#popup-modal").modal("openModal");
                event.preventDefault();
            }

            $("#verify-btn").on('click', function() {
                //$( "button.action.tocart.primary" ).trigger( "click" );
            });

            function verify() {
                
            }

        }
    );
</script>