<?php

/**
 * @category  Deloitte
 * @package   Deloitte_DeveloperTest
 * @author    Deloitte Team <info@deloitte.com>
 * @copyright 2020 Deloitte 
 * @link      https://www2.deloitte.com/
 */

/**
 *
 * @var $block Magento\Framework\View\Element\Template
 */
?>
<div id="popup-modal" style="display:none;">
    <div data-bind="scope: 'ageverification'">
        <!-- ko template: getTemplate() -->
        <!-- /ko -->
    </div>
</div>

<script type="text/x-magento-init">
    {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "ageverification": {
                            "component": "Deloitte_DeveloperTest/js/verification",
                            "template" : "Deloitte_DeveloperTest/verification-form"
                        }
                    }
                }
            }
        }
</script>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {

            var popup = modal(options, $('#popup-modal'));
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Verify your add before adding product in cart',
                buttons: [{
                    text: $.mage.__('Continue'),
                    class: '',
                    click: function() {
                        this.closeModal();
                    }
                }]
            };

            $('button.action.tocart.primary').click(function(e) {
                $("#popup-modal").modal("openModal");
                event.preventDefault();
            });

        }
    );
</script>